
CONFIG_GPIO=y
# Erlaubt die Nutzung von älteren ESP32 Chip-Revisionen
CONFIG_ESP32_USE_UNSUPPORTED_REVISION=y

# Empfohlen: Aktiviere Logging, um zu sehen, ob Hardware-Bugs auftreten
CONFIG_LOG=y

# Netzwerk-Support aktivieren
CONFIG_NETWORKING=y
CONFIG_NET_L2_WIFI_MGMT=y

# IPv4 Stack (meistens Standard für Heimnetze)
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y

# WiFi-Treiber für ESP32
CONFIG_WIFI=y
CONFIG_WIFI_ESP32=y


# Speicherverwaltung (Wichtig für den Netzwerk-Stack)
CONFIG_NET_PKT_RX_COUNT=10
CONFIG_NET_PKT_TX_COUNT=10
CONFIG_NET_BUF_RX_COUNT=20
CONFIG_NET_BUF_TX_COUNT=20